dist: xenial 
language: python
cache:
  directories:
    - $HOME/build/google/TensorNetwork/.pytype
    - $HOME/.cache/pip
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_travis.txt
  - pip install pylint pytest-cov codecov
# command to run tests
script:
  - pylint ./tensornetwork/
  - pytype ./tensornetwork -x **/*_test.py
  - pytest --cov=./
  - python3 setup.py build

after_success:
  - codecov
